version: '3.8'

services:
  web:
    image: nginx:alpine 
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html # bind mount volume (dependent on the directory structure and OS of the host)
    networks:
      - webnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # named volumes (managed by docker and stored within docker environment)
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data: